name: check-pr

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: yarn install

    - name: Check build
      run: yarn build

    - name: Check code
      run: yarn test
